function ijDescriptorRegister(imagePath1, imagePath2, saveDir, saveName)

if ~exist('saveName', 'var')
    saveDir = pwd;
end

if ~exist('saveName', 'var')
    saveName = 'TSeries-Registered-Channel-Stack.tif';
end

ij.IJ.open(imagePath1);
nP = strsplit(imagePath1, filesep);
im1 = nP{end};
ij.IJ.open(imagePath2);
nP = strsplit(imagePath2, filesep);
im2 = nP{end};

opts = "first_image=[" + im1 + "] " + ...
       "second_image=[" + im2 + "] " + ...
       "brightness_of=[Advanced ...] " + ...
       "approximate_size=[Advanced ...] " + ...
       "type_of_detections=[Maxima only] " + ...
       "subpixel_localization=[3-dimensional quadratic fit] " + ...
       "transformation_model=[Similarity (2d)] " + ...
       "images_pre-alignemnt=[Approxmiately aligned] " + ...
       "number_of_neighbors=5 " + ...
       "redundancy=2 " + ...
       "significance=3 " + ...
       "allowed_error_for_ransac=1 " + ...
       "choose_registration_channel_for_image_1=1 " + ...
       "choose_registration_channel_for_image_2=1 " + ...
       "create_overlayed " + ...
       "add_point_rois " + ...
       "interpolation=[Linear Interpolation]" + ...
       "detection_sigma=15.0000 " + ...
       "threshold=0.001";

ij.IJ.run("Descriptor-based registration (2d/3d)", opts);
ij.IJ.saveAs("Tiff", [saveDir filesep saveName]);
ij.IJ.selectWindow(saveName)
ij.IJ.close();
ij.IJ.selectWindow(im1);
ij.IJ.close();
ij.IJ.selectWindow(im1);
ij.IJ.close();