function ijXMLStitching(tileDir, outDir)

% Grid-wise stitching of ImageJ based on file metadata

xml = dir([tileDir, filesep, '*.xml']).name;

opts = "type=[Positions from file] " + ...
        "order=[Defined by image metadata] " + ...
        "multi_series_file=[" + tileDir + filesep + xml + "] " + ...
        "fusion_method=[Linear Blending] " + ...
        "regression_threshold=0.05 " + ...
        "max/avg_displacement_threshold=2.5 " + ...
        "absolute_displacement_threshold=3.5 " + ...
        "increase_overlap=0 " + ...
        "compute_overlap increase_overlap=0" + ...
        "computation_parameters=[Save computation time (but use more RAM)] " + ...
        "image_output=[Write to disk] " + ...
        "output_directory=[" + outDir + "]";

ij.IJ.run("Grid/Collection stitching", opts)

end