function ijTileConfigStitching(tileDir, outDir)

% This function will stitch together the images in tile dir based on the
% TileConfiguration file in the same directory.

tileConfigFile = dir([tileDir filesep 'TileConfiguration*.txt']).name;

opts =  "type=[Positions from file] " + ...
        "order=[Defined by TileConfiguration] " + ...
        "directory=[" + tileDir + "] " + ...
        "layout_file="  + tileConfigFile + " " + ...
        "fusion_method=[Linear Blending] " + ...
        "regression_threshold=0.30 " + ...
        "max/avg_displacement_threshold=2.50 " + ...
        "absolute_displacement_threshold=3.50 " + ...
        "computation_parameters=[Save computation time (but use more RAM)] " + ...
        "image_output=[Write to disk] " + ...
        "output_directory=[" + outDir + "]";

ij.IJ.run("Grid/Collection stitching", opts)

end



